### ISSUE TITLE
Hide the error page

### ISSUE THREAD

**Issue by Petah** [filp/whoops#256]
It would be nice if there was like a close button that removed or hide the whoops page. 

This would be handy in the case that there was some output flushed before an error, whoops will sit on top of it and it cannot be seen.

**Comment by denis-sokolov** [comment]
An interesting idea, but I don't think it warrants a UI space.
PrettyPageHandler is supposed to only be enabled in development, and there is no valuable information that could be outputted. And if by chance you really need to see what's there, just open developer tools and hide or delete the Whoops container DOM element.

**Comment by GRMule** [comment]
I came here looking for this exact thing.

As you said, the use-case is development. It is entirely plausible, likely even, that there is some debugging output behind the Whoops error message that would be useful in resolving the error that Whoops is reporting but doesn't make it into the formatted output. 

You're generally not wrong that it isn't a big deal to open dev tools and wipe the div out, *but*, that also takes time. If I don't already have the console loaded, or I'm working with a device without a convenient console... at any rate, I don't personally see why **not** have a fast and easy way to hide the output without extra steps.

I implemented it by adding an absolute positioned div with an X in it to the top/right of the header, so it didn't really take any additional UI space at all. A tiny addition to the .js file, and it's done. I created a fork and implemented these changes. Even though this bug was declined, I sent a pull request (PR #283) anyway because why not. No offense if you don't take it :)

**Comment by denis-sokolov** [comment]
@staabm, @GrahamCampbell, could you please provide your input?
I believe this is a barely useful feature and adding the UI for "quitting" the error is causing more confusion than benefit. What do you guys think?

**Comment by Petah** [comment]
A hotkey then? Better than opening up the debugger and deleting the element.

**Comment by denis-sokolov** [comment]
A hotkey alone is a cop out. Acceptable, but rather points to a problem not solved. Like a checkbox in advanced options. But this got me thinking. It's not a "hide the error page" feature. It's a "show me the raw output of my PHP script" feature. Instead of "X" we need something akin to "view raw script output", and instead of "+" we need "return to Whoops". Then it's entirely clear and is much easier to accept.
Thoughts?

**Comment by Petah** [comment]
Sounds good!

**Comment by GRMule** [comment]
Fair enough on the UI element being more descriptive. The intent with X was simply to keep it small, since the opposition to it seemed, initially, skepticism that dedicating UI space to this was a deal-breaker. I considered an icon, but I couldn't come up a good one. The exit icon (door with an arrow going out) came to mind, but that suffers from the same issue as an X. An eyeball ala Photoshop show/hide layer? A plain text X/+ seemed the smallest, lightest way to get the job done.

Regarding the hotkey, I saw the discussion about adding some more hotkeys and [escape] came to mind, but I didn't want to open that can of worms until it was clear that the feature generally would be happening.

I, personally, wouldn't describe this as "barely useful" (obviously, since I spent time on it). I am using the hider in the form that it currently exists in the PR almost every time I get an exception. I like the fancy formatted exception and stacktrace output, but I also have debugging text in the background and need to see it. Before I added the hider, I was opening the console and hiding the Whoops container (as you had suggested), which was clunky. I encourage you to consider that your debugging process isn't the same as everyone else's :)

I'll work on the notes on the PR, and await more discussion here.

**Comment by GRMule** [comment]
I used a base64 encoded image in the CSS to add these, replacing X/+. I also introduced some very specific instructions when the error page is hidden using css pseudo :before and :after, and a title attribute-based tooltip that changes with the show/hide state. The screenshots below depict the hover tooltip (mouse not captured in screengrab)

With error page visible (initial state):
![tooltip](https://cloud.githubusercontent.com/assets/2015304/7738187/c4b27d10-ff1f-11e4-8fb6-cae3d1933f77.png)

With error page hidden:
![tooltip2](https://cloud.githubusercontent.com/assets/2015304/7738188/c4b2c806-ff1f-11e4-82c6-430c22314bf4.png)

**Comment by denis-sokolov** [comment]
Alright, it seems your use case and the amount of effort you're ready to put in are considerable.
Let's wait for a few days to give a chance for @staabm and @GrahamCampbell to voice their opinions, and, if no major disagreements are raised, I think we shall include it.

**Comment by staabm** [comment]
I never ran into a situation in which I had to hide Whoops to see other content, but this might be related to our Whoops integration code (so which notices/warnings/.. are converted into exceptions and therefore will be handled by the pretty page handler).

I am not against this feature as I dont see any harm. Implementation details could be discussed in a PR.

**Comment by denis-sokolov** [comment]
Sorry for the delay, this fell out off my radar.
It's decided, we'll try to add this feature in #283!
